package com.example.findshelter.ShelterPointResponse

data class Row(
    val ar: Int,
    val areaCd: String,
    val areaNm: String,
    val chckMatterNightOpnAt: String,
    val chckMatterStayngPsblAt: String,
    val chckMatterWkendHdayOpnAt: String,
    val colrHoldArcndtn: Int,
    val colrHoldElefn: Int,
    val creDttm: String,
    val dtlAdres: String,
    val equptype: String,
    val la: Double,
    val lo: Double,
    val mngdptCd: String,
    val mngdpt_cd: String,
    val operBeginDe: String,
    val operEndDe: String,
    val restSeqNo: String,
    val restaddr: String,
    val restname: String,
    val rm: String,
    val updtDttm: String,
    val usePsblNmpr: Int,
    val useYn: String,
    val xcord: Double,
    val ycord: Double,
    val year: String
)